#!/bin/sh

set -e

case "$1" in
    purge)
        if [ ! -d /var/lib/mywebsql ]; then
            rm -r /var/lib/mywebsql
        fi
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
